baseURL = "https://lidesdk.github.io"
languageCode = "en-us"
theme = "after-dark"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
author = "Hernan Dario Cano"

[[menu.main]]
  name = "posts and news"
  weight = 1
  identifier = "post"
  url = "/"
[[menu.main]]
  name = "lide shell"
  weight = 2
  identifier = "lide-shell"
  url = "/shell/"
[[menu.main]]
  name = "lide framework"
  weight = 3
  identifier = "lide-framework"
  url = "/framework/"
