baseURL = "http://lidesdk.github.io"
languageCode = "en-us"
theme = "after-dark"
contentdir = "public/content"
publishdir = "public"
builddrafts = false
baseUrl = ""
canonifyurls = true
author = "Hernan Dario Cano"
disqusShortname = "lide team"

[[menu.main]]
  name = "- posts and news -"
  weight = 1
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "lide shell"
  weight = 2
  identifier = "lide-shell"
  url = "/shell/"
[[menu.main]]
  name = "lide framework"
  weight = 3
  identifier = "lide-framework"
  url = "/framework/"
